Repository jeffkaufman/nomic, pull requests merged in 2019-01, with the labels that each got.

#27 Add vesche to players.txt
  players/vesche
Labels: Add Player

#32 Player Scores
  README.md
  players/TheJhyde
  players/dchudz
  players/guoruibiao
  players/jeffkaufman
  players/jmitchell
  players/pavellishin
  players/sligocki
  players/tnelling
  players/vesche
Labels: Points

#43 approval after rejection: clear out old rejections
  validate.py
Labels: Bugfix

#58 Restore days_since_last_commit
  validate.py
Labels: Bugfix

#33 points: assign points for having PRs merged
  validate.py
Labels: Points

#63 github api proxy: use for 'next' links
  validate.py
Labels: reviewme

#68 players: remove guoruibiao for inactivity
  players/guoruibiao
Labels: reviewme

#67 remove dchudz as a player
  players/dchudz
Labels: reviewme

#65 github proxy: document caching settings
  validate.py
Labels: reviewme

#39 Show us the stragglers who didn't approve a PR.
  validate.py
Labels: Voting, reviewme

#49 Allow transferring points with the consent of those involved
  validate.py
Labels: Points, reviewme

#73 winning: make someone's chance of winning proportional to points
  validate.py
Labels: reviewme

#87 Add tnelling as a player
  players/tnelling/bonuses/initial
Labels: reviewme

#88 Updating comments
  rules/0.3-allow-points-transfer.py
Labels: reviewme

#94 Add pavellishin as a player
  players/pavellishin/bonuses/initial
Labels: reviewme
